name: rzd
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  localization: 2.1.1
  collection: 1.19.1
  go_router: ^17.0.1
  provider: ^6.1.5+1
  searchfield: ^1.4.0
  dio: ^5.9.0
  cupertino_icons: ^1.0.8
  custom_accordion: ^1.0.0
  intl: ^0.20.2
  web: 1.1.1
  cupertino_calendar_picker: ^2.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true